fix: respawnPlayer() will cause the player fall into an abnormal state
zly2006/Enclosure pull request #33
Opened 2023-09-16 19:51 UTC by SakuraWald

PlayerManager#respawnPlayer() will cause the player to fall into an abnormal state, which means that the player's real position is still no change, and the player can't break any blocks. (And then the player will be kicked because of "Flying too long", and then the player can't even join the server anymore.

To stop the abuse of PlayerManager#respawnPlayer(), and change the default solution to teleport the player to the spawn of the overworld. (This may not be the best solution, maybe a config option to set where to teleport ?)

2023-09-16 19:54 UTC, zly2006 commented
maybe you should merge upstream first and then commit your changes

then do a force push, so commit history can be shorter and clearer

2023-09-16 20:37 UTC, SakuraWald commented
> maybe you should merge upstream first and then commit your changes
> 
> then do a force push, so commit history can be shorter and clearer

It's done

2023-09-17 17:00 UTC, zly2006 requested changes

2023-09-17 17:00 UTC, zly2006 commented on src/main/kotlin/com/github/zly2006/enclosure/EnclosureArea.kt
> +            player.teleport(overworld, spawnPos.x.toDouble(), spawnPos.y.toDouble(), spawnPos.z.toDouble(), 0f, 0f)
you should +0.5 for block pos on x/z so that the player will tp to the center of the block

2023-09-17 17:39 UTC, zly2006 approved these changes

2023-09-17 17:39 UTC, merged